### ISSUE TITLE
Unicode typing causes build error on WS2017

### ISSUE THREAD

**Issue by Mango-kid** [fantastory/AMQP-CPP#5]
If someone can confirm my changes wont break this error reporting and I can create a pull request. 
```cpp
if (code != 0) throw std::runtime_error(gai_strerror(code));
```
to
```cpp
if (code != 0) throw std::runtime_error(gai_strerrorA(code));
```

**Comment by fantastory** [comment]
The project was ported from linux and the target was to keep it with source project.
Linux does not have gai_strerror.
Do you really need Project _options/Advanced/Character_set = Unicode?
Or could you switch to NotSet or MultiByte?

Actually Unicode uses twice more memory especially when writing large files to disc.

**Comment by fantastory** [comment]
I would rather throw custom exception and a constructor Exception(wchar_t *) to it

It is in src\addressinfo.h

Solution would be to throw AMQP::Exception from include\exception.h

And add there a AMQP::Exception(wchar_t *) constructor, with wchar_T to char conversion and protect it with #ifdef __mscver__ #endif.

But since I am not maintaining it, and if I do I want to rewrite it back to be close to Copernica branch again. it means you better just fork and use gai_strerrorA.
